baseurl = "https://www.bjaytang.com/"
metaDataFormat = "yaml"
title = "Brian Jay Tang"
theme = "blist"
enableEmoji = true

DefaultContentLanguage = "en"
DefaultContentLanguageInSubdir = true
[languages]
  [languages.en]
    contentDir = "content/en" #English
    weight = 1
    languageName = "English"
    [languages.en.params]
      introTitle = "Hello World! I'm Brian Tang"
      introSubtitle = "I’m a 1st year Computer Science PhD student at the University of Michigan. I work on research in the intersection of usable privacy and machine learning."
      introPhoto = "/images/profile.jpg"
      logo = "/blist-logo.png"

    [[languages.en.menu.main]]
        name = "About"
        url = "page/about/"
        weight = 1

    [[languages.en.menu.main]]
        name = "Projects"
        url = "projects"
        weight = 2

    [[languages.en.menu.main]]
        name = "News"
        url = "news"
        weight = 3

    [[languages.en.menu.main]]
        name = "Teaching"
        url = "page/teaching/"
        weight = 4

    [[languages.en.menu.main]]
        name = "Service"
        url = "page/service/"
        weight = 5

    [[languages.en.menu.main]]
        name = "Tags"
        url = "tags"
        weight = 6

  [languages.de]
    contentDir = "content/de" # Deutsch
    weight = 2
    languageName = "Deutsch"
    title = "Blist (mehrsprachig)"
    description = "Modernes Blog-Theme für Ihre Hugo-Site."
    [languages.de.params]
      introTitle = "Hallo, ich bin Katheryn Fox"
      introSubtitle = "26-jährige Junior-Entwicklerin, die Spaß an sozialen Kartenspielen, Bloggen und Malen hat"
      introPhoto = "/picture.jpg"
      logo = "/blist-logo-de.png"
    [[languages.de.menu.main]]
        name = "Blog"
        url = "blog"
        weight = 1

    [[languages.de.menu.main]]
        name = "Über mich"
        url = "page/about/"
        weight = 2

    [[languages.de.menu.main]]
        name = "Tags"
        url = "tags"
        weight = 3
        
  [languages.fr]
    contentDir = "content/fr" #French
    weight = 1
    languageName = "Français"
    [languages.fr.params]
      introTitle = "Salut! Je suis Katheryn Fox"
      introSubtitle = "Développeuse junior de 26 ans qui adore les jeux de société, le blogging et la peinture"
      introPhoto = "/picture.jpg"
      logo = "/blist-logo.png"
    [[languages.fr.menu.main]]
        name = "Blog"
        url = "blog"
        weight = 1

    [[languages.fr.menu.main]]
        name = "À propos"
        url = "page/about/"
        weight = 2

    [[languages.fr.menu.main]]
        name = "Tags"
        url = "tags"
        weight = 3
        
  [languages.dy]
    contentDir = "content/dy" #Example language
    weight = 3
    languageName = "Test Language"

[params]
  # Enable the darkmode toggle in header
  darkModeToggle = true
  
  # Enable search in header
  enableSearch = true

  # Custom copyright - optional
  copyright = "Copyright © 2022 - Brian Tang · All rights reserved"
  favicon = "/favicon.svg"

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-blue-100"

  # The page bundle that is shown on the front page
  frontBundle = "projects"
  varun = "Varun Chandrasekaran"
  varunURL = "https://pages.cs.wisc.edu/~chandrasekaran/"
  kassem = "Kassem Fawaz"
  kassemURL = "https://kassemfawaz.com/"
  shin = "Kang G. Shin"
  shinURL = "https://web.eecs.umich.edu/~kgshin/"
  somesh = "Somesh Jha"
  someshURL = "https://pages.cs.wisc.edu/~jha/"
  harrison = "Harrison Rosenberg"
  harrisonURL = "https://wiscprivacy.com/member/member_harrison/"
  papernot = "Nicolas Papernot"
  papernotURL = "https://www.papernot.fr/"
  duc = "Duc Bui"
  ducURL = "https://ducbui.com/"
  xi = "Xi Wu"
  xiURL = "http://andrewxiwu.github.io/"
  chuhan = "Chuhan Gao"
  chuhanURL = "https://scholar.google.com/citations?user=3LKG2koAAAAJ&hl=en"
  suman = "Suman Banerjee"
  sumanURL = "https://pages.cs.wisc.edu/~suman/"
  bilge = "Bilge Mutlu"
  bilgeURL = "http://bilgemutlu.com/"
  dakota = "Dakota Sullivan"
  dakotaURL = "https://peopleandrobots.wisc.edu/staff/sullivan-dakota/"
  bengisu = "Bengisu Cagiltay"
  bengisuURL = "https://peopleandrobots.wisc.edu/staff/cagiltay-bengisu/"
    


[params.homepage.social]
  # Global params xommon for both languages
  title = "Follow or contact me"
  description = "I publish and open-source my work. I also occasionally post random thoughts."
  github = "https://github.com/byron123t"
  scholar = "https://scholar.google.com/citations?user=pgkhBk8AAAAJ&hl=en"
  linkedin = "https://linkedin.com/in/bjaytang"
  twitter = "https://twitter.com/byron123t"
  instagram = "https://www.instagram.com/asianturtless/"
  reddit = "https://reddit.com/user/byron123t"
  email = "bjaytang@umich.edu"

[[menu.main]]
  name = "About"
  url = "/about"

[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
